name: Build and Deploy to Azure Static Web Apps

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
        
    - name: Build
      run: |
        echo "Environment variables during build:"
        echo "REACT_APP_COSMOS_ENDPOINT: $REACT_APP_COSMOS_ENDPOINT"
        echo "REACT_APP_COSMOS_KEY: ${REACT_APP_COSMOS_KEY:0:20}..."
        npm run build
      env:
        REACT_APP_COSMOS_ENDPOINT: ${{ secrets.REACT_APP_COSMOS_ENDPOINT }}
        REACT_APP_COSMOS_KEY: ${{ secrets.REACT_APP_COSMOS_KEY }}
        
    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "/"
        output_location: "dist"